version: '2'

services:

  fs:
    image: tianon/true
    volumes:
      - ./mysql-datadir:/var/lib/mysql
      - ./backups:/backups

  db:
    image: mariadb:10.1.14
#    image: mysql:5.7
    env_file: .env
    volumes_from:
      - fs

  cco:
    build: ./cco-tools
    entrypoint: sh -c "./wait-for-it.sh --timeout=40 db:3306 && mvn clean install"
    volumes:
      - ./cco-tools:/usr/src/myapp
    depends_on:
      - db
    links:
      - db

  backup:
    image: alpine
    command: sh -c "tar cvfz /tmp/db-backup.tgz /var/lib/mysql"
    volumes_from:
      - db


